name: database_repository
description: Dart package which manages database queries.
publish_to: 'none'
version: 1.0.0

environment:
   sdk: '>=3.4.0 <4.0.0' 
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  meta: ^1.9.1
  cloud_firestore: ^6.0.2
  authentication_repository:
    path: ../authentication_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
