platform :ios, '15.0'

use_frameworks! :linkage => :static
use_modular_headers!

ENV['FIREBASE_IOS_SDK_VERSION'] = '12.2.0'

require File.expand_path(File.join('..', 'Flutter', 'podhelper'), __FILE__)
flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
