platform :ios, '15.0'

use_frameworks! :linkage => :static
use_modular_headers!

ENV['FIREBASE_IOS_SDK_VERSION'] = '12.2.0'

require File.expand_path(File.join('..', 'Flutter', 'podhelper'), __FILE__)
flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'

      next if target.name == 'Runner'

      # Pod targets must not inherit manual signing or provisioning profiles.
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
      config.build_settings.delete('PROVISIONING_PROFILE_SPECIFIER')
      config.build_settings.delete('PROVISIONING_PROFILE')
    end
  end
end
