default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    bundle_id = ENV['IOS_BUNDLE_IDENTIFIER'] || "com.giatocphamdinh.familytree"
    profile_name = ENV['IOS_PROFILE_NAME'] || "GiatocphamdinhAppEco"
    profile_specifier = ENV['IOS_PROFILE_SPECIFIER'] || profile_name
    dev_team = ENV['IOS_DEVELOPMENT_TEAM'] || "DLX7252NAD"
    code_sign_identity = ENV['IOS_CODE_SIGN_IDENTITY'] || "Apple Distribution"

    # Set signing
    update_code_signing_settings(
      path: "Runner.xcodeproj", # hoặc .xcworkspace nếu có
      use_automatic_signing: false,
      team_id: dev_team,
      bundle_identifier: bundle_id
    )

    # Import cert
    import_certificate(
      certificate_path: "fastlane/certs/Certificates.p12",
      certificate_password: ENV.fetch("IOS_CERT_PASSWORD", "Cotdinh123"),
      keychain_name: ENV.fetch("KEYCHAIN_NAME", "login"),
      keychain_password: ENV.fetch("KEYCHAIN_PASSWORD", "1234")
    )

    # Install provisioning profile
    profile_path = ENV['IOS_PROFILE_PATH'] || "fastlane/profiles/#{profile_name}.mobileprovision"
    install_provisioning_profile(path: profile_path)
    sh("flutter --version")
    sh("flutter clean")
    sh("flutter pub get")
    sh("flutter build ios --release --no-codesign")
    # Build
    build_app(
      scheme: "Runner",
      workspace: "./Runner.xcworkspace",
      destination: "generic/platform=iOS",
      sdk: "iphoneos",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          bundle_id => profile_specifier
        }
      },
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=#{dev_team} CODE_SIGN_IDENTITY='#{code_sign_identity}' PROVISIONING_PROFILE_SPECIFIER='#{profile_specifier}' PRODUCT_BUNDLE_IDENTIFIER='#{bundle_id}' IPHONEOS_DEPLOYMENT_TARGET=15.0"
    )

    # Upload using API key
    app_store_connect_api_key(
      key_id: ENV.fetch("APPSTORE_KEY_ID", "5ZBNQGXYVF"),
      issuer_id: ENV.fetch("APPSTORE_ISSUER_ID", "397aeb4e-abfe-4060-a3c9-6529c136bfb9"),
      key_filepath: ENV.fetch("APPSTORE_KEY_PATH", "fastlane/keys/AuthKey_5ZBNQGXYVF.p8")
    )

    upload_to_testflight
  end
end
