default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # Set signing
    update_code_signing_settings(
      path: "Runner.xcodeproj", # hoặc .xcworkspace nếu có
      use_automatic_signing: false,
      team_id: "DLX7252NAD",
      bundle_identifier: "com.giatocphamdinh.familytree"
    )

    # Import cert
    import_certificate(
      certificate_path: "fastlane/certs/Certificates.p12",
      certificate_password: ENV.fetch("IOS_CERT_PASSWORD", "Cotdinh123"),
      keychain_name: ENV.fetch("KEYCHAIN_NAME", "login"),
      keychain_password: ENV.fetch("KEYCHAIN_PASSWORD", "1234")
    )

    # Install provisioning profile
    install_provisioning_profile(
      path: ENV.fetch("IOS_PROFILE_PATH", "fastlane/profiles/GiatocphamdinhAppEco.mobileprovision")
    )
    sh("flutter --version")
    sh("flutter clean")
    sh("flutter pub get")
    sh("flutter build ios --release --no-codesign")
    # Build
    build_app(
      scheme: "Runner",
      workspace: "./Runner.xcworkspace",
      destination: "generic/platform=iOS",
      sdk: "iphoneos",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.giatocphamdinh.familytree" => "GiatocphamdinhAppEco"
        }
      },
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=DLX7252NAD CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='GiatocphamdinhAppEco' IPHONEOS_DEPLOYMENT_TARGET=15.0"
    )

    # Upload using API key
    app_store_connect_api_key(
      key_id: ENV.fetch("APPSTORE_KEY_ID", "5ZBNQGXYVF"),
      issuer_id: ENV.fetch("APPSTORE_ISSUER_ID", "397aeb4e-abfe-4060-a3c9-6529c136bfb9"),
      key_filepath: ENV.fetch("APPSTORE_KEY_PATH", "fastlane/keys/AuthKey_5ZBNQGXYVF.p8")
    )

    upload_to_testflight
  end
end
