default_platform(:android)

platform :android do
  before_all do
    UI.user_error!("Set DEMO_SECRET environment variable before running Fastlane.") if (ENV["DEMO_SECRET"].nil? || ENV["DEMO_SECRET"].empty?)
  end

  desc "Run Flutter unit tests"
  lane :tests do
    sh("flutter test --dart-define=DEMO_SECRET=#{ENV['DEMO_SECRET']}")
  end

  desc "Build a debug APK"
  lane :build_debug do
    sh("flutter build apk --debug --dart-define=DEMO_SECRET=#{ENV['DEMO_SECRET']}")
  end

  desc "Build a release App Bundle"
  lane :build_release do
    sh("flutter build appbundle --release --dart-define=DEMO_SECRET=#{ENV['DEMO_SECRET']}")
  end

  desc "Upload release bundle to Play internal testing"
  lane :deploy_internal do
    build_release
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_apk: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true
    )
  end
end
